### ISSUE TITLE
Use with Blaze3 files

### ISSUE THREAD

**Issue by EdwinHernandezG** [VolkerH/Ultramicroscope2BigStitcher#5]
We want to try the app to convert the Blaze3 files generated to be used in big stitcher.

The file structure is similar, but I faced this error:

```
Input folder E:/210706_MouseOvary_control3_Right_6-TOPRO3_adaptiveblend_12x_1z_14-39-20
Output folder E:/MouseOvCtrl
2D projection False
2D volume True
xy scale um/pix 0.54
z scale um/pix 2.0
Zspacing: 2.0
XYspacing: 0.54
Processing 3136 tiles.
Processing 1 out of 3136:
reading E:\210706_MouseOvary_control3_Right_6-TOPRO3_adaptiveblend_12x_1z_14-39-20\14-39-20_MouseOvary_control3_Right_6-TOPRO3_adaptiveblend_12x_1z_Blaze[00 x 00]_C00_xyz-Table Z0000.ome.tif
(784, 2559, 2160)
finished reading stack
xyz is [-12302.875977 -23970.224609   1140.3125  ]
Traceback (most recent call last):
  File "C:\Users\Linux\.conda\envs\um2b\lib\site-packages\um2bs\background_worker.py", line 70, in run
    result = self.fn(*self.args, **self.kwargs)
  File "um2bs_gui.py", line 144, in _process
    zspacing=float(self.lineedit_zspacing.text()),
  File "C:\Users\Linux\.conda\envs\um2b\lib\site-packages\um2bs\process_um_folder.py", line 292, in generate_big_stitcher
    calibration=(1, 1, zspacing / xyspacing),
  File "C:\Users\Linux\.conda\envs\um2b\lib\site-packages\npy2bdv\npy2bdv.py", line 496, in append_view
    assert len(stack.shape) == 3, "Stack should be a 3-dimensional numpy array (z,y,x)"
AssertionError: Stack should be a 3-dimensional numpy array (z,y,x)
```

Any ideas about what can be happening?

Thanks for your help in advance.

**Comment by VolkerH** [comment]
Hi @EdwinHernandezG 


Sorry, I did not see this earlier.

There were some breaking API changes in npy2bdv (see https://github.com/nvladimus/npy2bdv/blob/master/CHANGELOG.md)
My installation instructions don't specify a version number, maybe try with 
`pip install npy2bdv==1.0.1` or some of the other versions.

The error message suggest that the array bneing passed in does not have the required shape (z,y,x). I'm not sure that's related to npy2bdv (although that's what I would check first).  It could also be that you have an additional channel dimension or you are missing the z dimension.

I am not familiar with the Blaze3 file format and I don't know whether you made any additional code adjustments to accomodate the Blaze3 format, so I can only guess. The npy2bdv changes would be the first thing I would check.
Without  knowledge of the format or a test data set it is hard to diagnose remotely but let me know how you're going.

**Comment by VolkerH** [comment]
I haven't heard back, so will close this for now. Feel free to reopen.
