### ISSUE TITLE
Problem setting spacing

### ISSUE THREAD

**Issue by EdwinHernandezG** [VolkerH/Ultramicroscope2BigStitcher#6]
I made a fresh installation in Linux in a new conda environment using pip, and the program worked properly (I can create the project), but I cannot change the spacing on the GUI interface.

Ideas about how I can fix this behavior?

Again, thanks for the tool.

**Comment by VolkerH** [comment]
Ah, I should have read this before trying to answer the other issue.

Can you be more specific what the problem is? A screenshot of the problem could help and maybe the PyQt version. Are there any messages on the console?

**Comment by VolkerH** [comment]
I haven't heard back, so will close this for now. Feel free to reopen.
